Repository Safe-DS/API-Editor, pull requests merged in 2022-06, with the labels that each got.

#540 feat(gui): parameter assignment filter
  api-editor/gui/src/common/FilterHelpButton.tsx
  api-editor/gui/src/features/annotatedPackageData/model/AnnotatedPythonParameter.ts
  api-editor/gui/src/features/packageData/model/PythonParameter.ts
  api-editor/gui/src/features/packageData/model/filters/ParameterAssignmentFilter.ts
  api-editor/gui/src/features/packageData/model/filters/filterFactory.ts
Labels: needs review

#464 build: bump Python to 3.10
  .github/workflows/main.yml
  .github/workflows/pr.yml
  package-parser/README.md
  package-parser/poetry.lock
  package-parser/pyproject.toml
Labels: DO NOT MERGE

#648 docs: Creating manual for api-editor
  api-editor/img/annotation.jpg
  api-editor/img/boundary.jpg
  api-editor/img/constant.jpg
  api-editor/img/enum.jpg
  api-editor/img/filter.jpg
  api-editor/img/group.jpg
  api-editor/img/heat_map.jpg
  api-editor/img/import.jpg
  api-editor/img/navigation.jpg
  api-editor/manual.md
Labels: documentation
